(function(){
  var book=window.LAOZI_DE_WORKING;if(!book)return;
  var state={chapter:Math.min(40,Math.max(1,+(localStorage.getItem('tiangong-laozi-chapter')||1))),tab:'reading',expanded:false,sidebarCollapsed:false};
  var $=function(id){return document.getElementById(id)},doors=$('doors'),records=$('records'),sheet=$('sheet'),active=false;
  var link=document.createElement('link');link.rel='stylesheet';link.href='laozi_reader.css';document.head.appendChild(link);
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function chapter(){return book.chapters[state.chapter-1]}
  function restore(){active=false;document.body.classList.remove('laozi-reading','library-rail-collapsed')}
  function ensureRailToggle(){var folio=document.querySelector('.folio'),toggle=folio.querySelector('.library-rail-toggle');if(!toggle){toggle=document.createElement('button');toggle.className='library-rail-toggle';toggle.type='button';toggle.style.display='grid';toggle.setAttribute('aria-label','收起藏书阁侧栏');toggle.innerHTML='<span>‹</span>';toggle.onclick=function(){state.sidebarCollapsed=!state.sidebarCollapsed;syncRail()};folio.appendChild(toggle)}return toggle}
  function syncRail(){var toggle=ensureRailToggle();document.body.classList.toggle('library-rail-collapsed',state.sidebarCollapsed);toggle.setAttribute('aria-label',state.sidebarCollapsed?'展开藏书阁侧栏':'收起藏书阁侧栏');toggle.setAttribute('aria-expanded',String(!state.sidebarCollapsed));toggle.innerHTML='<span>'+(state.sidebarCollapsed?'›':'‹')+'</span>'}
  function renderCatalogue(){
    $('catTitle').textContent='藏 书 阁';$('catNote').textContent='点击书名展开章节；收起时只保留书目与阅读进度。';
    records.innerHTML='<div class="library-list"><section class="library-book '+(state.expanded?'open':'')+'"><button class="library-book-head" data-laozi-book="toggle" aria-expanded="'+state.expanded+'"><span class="library-spine">老<br>子</span><span class="library-book-meta"><b>'+esc(book.title)+'</b><small>'+esc(book.subtitle)+'</small><i>读至第 '+state.chapter+' 章 · '+Math.round(state.chapter/book.chapters.length*100)+'%</i></span><span class="library-chevron">⌄</span></button>'+(state.expanded?'<div class="library-chapter-drawer"><div class="laozi-chapters">'+book.chapters.map(function(c){return'<button class="laozi-chapter '+(c.number===state.chapter?'active':'')+'" data-laozi-chapter="'+c.number+'"><b>第 '+c.number+' 章</b><span>'+esc(c.title)+'</span></button>'}).join('')+'</div><div class="laozi-progress"><div class="laozi-progress-label"><span>本书阅读进度</span><span>'+state.chapter+' / '+book.chapters.length+'</span></div><div class="laozi-progress-track"><i style="width:'+(state.chapter/book.chapters.length*100)+'%"></i></div></div></div>':'')+'</section></div>';
  }
  function renderTabs(c){$('pageTabs').innerHTML='<button class="page-tab '+(state.tab==='reading'?'active':'')+'" data-laozi-tab="reading">译 读</button><button class="page-tab '+(state.tab==='notes'?'active':'')+'" data-laozi-tab="notes">札 记'+(c.notes.length?'<em>'+c.notes.length+'</em>':'')+'</button><button class="page-tab '+(state.tab==='about'?'active':'')+'" data-laozi-tab="about">说 明</button>'}
  function reading(c){var pairs=c.original.map(function(o,i){return'<div class="laozi-pair"><p class="laozi-original">'+esc(o)+'</p><p class="laozi-translation">'+esc(c.translation[i]||'【本段译读待补】')+'</p></div>'}).join('');return'<div class="laozi-sheet"><div class="laozi-section-label">原文与白话译读</div>'+pairs+'<div class="laozi-section-label">本章关键词</div><div class="laozi-keywords">'+c.keywords.map(function(k){return'<span>'+esc(k)+'</span>'}).join('')+'</div>'+(c.understanding?'<div class="laozi-section-label">本章理解</div><div class="laozi-understanding"><small>工作版理解 · 可继续修订</small>'+esc(c.understanding)+'</div>':'')+(c.notes.length?'<div class="laozi-note-preview" data-open-notes>本章有 '+c.notes.length+' 条译读札记：'+esc(c.notes.map(function(n){return n.type}).join('、'))+'。点击查看</div>':'')+'</div>'}
  function notes(c){return'<div class="laozi-sheet"><div class="laozi-section-label">译读札记</div>'+(c.notes.length?c.notes.map(function(n){return'<article class="laozi-note-card"><div class="laozi-note-head"><span class="laozi-note-type">'+esc(n.type)+'</span><b class="laozi-note-target">'+esc(n.target)+'</b></div><p>'+esc(n.text)+'</p><div class="laozi-note-impact">影响：'+esc(n.impact)+'</div></article>'}).join(''):'<div class="laozi-note-empty">本章暂时没有影响理解的重要札记。</div>')+'</div>'}
  function about(c){return'<div class="laozi-sheet"><div class="laozi-about"><h3>'+esc(book.title)+' · '+esc(book.subtitle)+'</h3><p>'+esc(book.notice)+'</p><div class="laozi-about-list"><div>当前章节原文来源：'+esc(c.source)+'</div><div>章节状态：'+esc(c.status)+'</div><div>第一、二章保留用户既有译读；第三至第四十章为续译工作版。</div><div>札记只记录影响理解的问题，不把普通异文变成逐字校勘。</div></div></div></div>'}
  function nav(){return'<div class="laozi-nav"><button data-laozi-nav="prev" '+(state.chapter===1?'disabled':'')+'>← 上一章</button><span>德篇 · '+state.chapter+' / '+book.chapters.length+'</span><button data-laozi-nav="next" '+(state.chapter===book.chapters.length?'disabled':'')+'>下一章 →</button></div>'}
  function renderPage(){var c=chapter();$('seal').innerHTML='老<br>子';$('entryTitle').textContent='第'+c.number+'章 · '+c.title;$('entryMeta').textContent=book.subtitle+' · '+c.source;document.querySelector('.draft').textContent=c.status;renderTabs(c);sheet.innerHTML=(state.tab==='reading'?reading(c):state.tab==='notes'?notes(c):about(c))+nav();$('makeBtn').style.display='none'}
  function render(){active=true;document.body.classList.add('laozi-reading');renderCatalogue();renderPage();syncRail()}
  function activate(){state.tab='reading';state.expanded=false;state.sidebarCollapsed=false;render()}
  doors.addEventListener('click',function(e){var b=e.target.closest('[data-cat]');if(!b)return;restore();setTimeout(function(){if(b.dataset.cat==='books')activate()},0)},true);
  records.addEventListener('click',function(e){var bookToggle=e.target.closest('[data-laozi-book]');if(bookToggle){e.preventDefault();e.stopImmediatePropagation();state.expanded=!state.expanded;renderCatalogue();return}var b=e.target.closest('[data-laozi-chapter]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();state.chapter=+b.dataset.laoziChapter;state.tab='reading';state.sidebarCollapsed=true;localStorage.setItem('tiangong-laozi-chapter',state.chapter);render();document.querySelector('.page').scrollTop=0},true);
  $('pageTabs').addEventListener('click',function(e){var b=e.target.closest('[data-laozi-tab]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();state.tab=b.dataset.laoziTab;renderPage();document.querySelector('.page').scrollTop=0},true);
  sheet.addEventListener('click',function(e){if(e.target.closest('[data-open-notes]')){state.tab='notes';renderPage();document.querySelector('.page').scrollTop=0}var b=e.target.closest('[data-laozi-nav]');if(!b)return;var next=state.chapter+(b.dataset.laoziNav==='next'?1:-1);if(next<1||next>book.chapters.length)return;state.chapter=next;state.tab='reading';localStorage.setItem('tiangong-laozi-chapter',state.chapter);render();document.querySelector('.page').scrollTop=0});
})();
