(function(root){
const numbers={
0:{title:'留白',keywords:['开放','多方向','自我选择'],archetype:'0不把课题集中在某一种固定倾向上，更像一片需要根据现实处境作出选择的开放空间。',strength:'你有机会用不同方式回应问题，而不必被单一路径限制。',shadow:'方向过多时，也可能难以判断真正需要处理的重点。',growth:'先辨认眼前最具体的课题，再决定要发展哪一种能力。'},
1:{title:'开创',keywords:['独立','行动','方向'],archetype:'1关注的是独立、主动和为自己确定方向。它让人把注意力放在“我要怎样开始”以及“什么是我的选择”上。',strength:'你更容易主动开始、清楚表达立场，并在没有现成答案时自己寻找方向。',shadow:'走得太重时，坚定会变成固执，独立也可能变成不愿求助。',growth:'保留行动力，同时练习倾听、协作和在必要时调整方向。'},
2:{title:'调和',keywords:['关系','感受','合作'],archetype:'2关注关系、合作和对他人反应的感受力。它让人更留意气氛、分寸，以及双方怎样才能真正配合。',strength:'你容易察觉细微变化，愿意倾听，也懂得在关系中寻找共同点。',shadow:'太在意回应时，体贴可能变成迎合，犹豫也会让自己的需要退到后面。',growth:'在照顾关系的同时说清自己的想法，让温和与边界同时存在。'},
3:{title:'表达',keywords:['表达','创造','分享','社交'],archetype:'3关注表达、创造和让想法被看见。它通过语言、作品、幽默或交流，把内在感受带到外部世界。',strength:'你容易产生点子，也懂得用有感染力的方式沟通和带动气氛。',shadow:'兴趣太多时容易分散，表达也可能停留在开头，没有变成完整成果。',growth:'选择真正重要的想法持续完成，让灵感不只是一时兴起。'},
4:{title:'建设',keywords:['秩序','稳定','建设','落实'],archetype:'4关注怎样把事情真正建立起来。它重视规划、执行、责任和长期积累，而不只是一时的灵感。',strength:'你容易看到一件事怎样才能落地，也更重视可靠、秩序和长期结果。',shadow:'走得太重时，稳定会变成僵化，认真会变成控制，变化也容易令人不安。',growth:'保留踏实，同时给变化留出空间。真正稳定的安排，是能够经得起调整。'},
5:{title:'探索',keywords:['自由','变化','体验','适应'],archetype:'5关注变化、自由和亲自体验世界。它需要流动、尝试和新鲜感，也会推动人不断拓展边界。',strength:'你适应变化快，愿意尝试，也容易从不同经验中找到新的可能。',shadow:'追求变化过头时，选择会变得分散，承诺和持续完成也可能令人受限。',growth:'为自由建立基本节奏，让探索能够积累成真正属于你的经验。'},
6:{title:'守护',keywords:['责任','照顾','关系','和谐'],archetype:'6关注责任、关系和怎样营造一个让人安心的环境。它既包含照顾别人，也包含对承诺、品质和归属感的重视。',strength:'你愿意承担，能察觉身边人的需要，也擅长把关系和生活安排得更稳定。',shadow:'承担过多时，照顾会变成干预，责任会变成压力，也容易忘记自己的边界。',growth:'让关心保留空间，分清哪些责任真正属于你，并允许别人用自己的方式成长。'},
7:{title:'求知',keywords:['分析','观察','求知','内省'],archetype:'7关注理解事物背后的原因：观察、分析、独立思考，以及给自己留出安静思考的空间。',strength:'你能够深入研究、独立判断，也愿意追问表面答案背后的根据。',shadow:'思考走得太远时，谨慎会变成怀疑，独处会变成抽离，也可能迟迟不行动。',growth:'保留深度，同时用现实经验验证判断；想清楚以后，也让自己向前走一步。'},
8:{title:'实现',keywords:['成果','资源','影响','责任'],archetype:'8关注现实成果、资源运用和力量带来的责任。它要求人理解目标、交换、边界以及怎样让影响力落到现实。',strength:'你有组织资源、推动结果和面对现实压力的能力，也更懂得衡量长期回报。',shadow:'结果感太强时，效率会压过感受，掌控也可能取代真正的合作。',growth:'让成果与价值观一致，既敢于承担力量，也记得力量需要被负责地使用。'},
9:{title:'整合',keywords:['整体','理想','共情','完成'],archetype:'9关注整体、意义和一个阶段如何完成。它容易把个人经验放进更大的背景，也会留意事情对他人的影响。',strength:'你能看见不同立场之间的联系，具有同理心，也愿意为有意义的事情投入。',shadow:'理想太重时容易耗竭，过度共情也会让你难以区分自己的感受和别人的需要。',growth:'保留理想，同时接受现实的限度；该结束时允许结束，把关心落在具体行动上。'},
11:{title:'启示',keywords:['直觉','灵感','敏锐','分辨'],archetype:'11是大师数字，强调直觉、联想和对环境细节的敏锐度。它不是更高等级，而是需要学习如何承接较强的感受与灵感。',strength:'你容易捕捉未被说出口的信息，也能从细节中形成有启发性的联想。',shadow:'接收太多时容易紧张、想得太远，或难以判断哪些感受真正重要。',growth:'建立稳定的现实锚点，区分直觉、情绪和想象，再把灵感转化为可验证的表达。'},
22:{title:'筑梦',keywords:['愿景','结构','实现','责任'],archetype:'22是大师数字，强调把较大的愿景变成可以运行的现实结构。它不是天赋等级，而是一种同时面对理想和执行的要求。',strength:'你能够看见长期蓝图，也有把资源、步骤和人组织起来的潜力。',shadow:'目标过大时容易背负过多压力，或因为害怕做不好而迟迟不开始。',growth:'把愿景拆成能完成的阶段，让宏大目标从稳定的小步骤中逐渐成形。'},
33:{title:'疗愈',keywords:['关怀','教导','服务','边界'],archetype:'33是大师数字，强调关怀、教导和有意识地服务他人。它不是牺牲自己的要求，而是学习怎样让给予真正有效。',strength:'你能够理解他人的需要，也有用经验、表达或陪伴支持别人的能力。',shadow:'关怀失去边界时容易过度负责，甚至把自己的价值建立在被需要上。',growth:'让给予包含边界和选择，先照顾好自身资源，再决定怎样支持别人。'}
};
const concentration=['空缺','存在','突出','强化','高浓度'];
const positionIntro={birthday:'生日数更像你比较自然的一面，描述容易随身带着的天赋和行为习惯。',attitude:'态度数说的是：进入新环境、遇到新的人或状况时，你最先启动的反应方式。',birthYear:'出生年数是辅助数字，用来观察出生年份带来的基础色彩。它不像生命路径那样决定整条主线，更像背景里一直存在的倾向。'};
function number(n){return numbers[n]||numbers[0]}
function compound(steps){return steps.length>1?`${steps[0]}是出生日期数字相加后的复合结果，继续归约后得到${steps.at(-1)}。因此${steps.at(-1)}是主要数字，${steps[0]}保留了这条路径形成的过程信息。`:''}
function lifePath(n,steps){const d=number(n);return{title:`生命路径 · ${n}`,lead:`${d.archetype} 对生命路径${n}来说，这不是一项短期任务，而是会在人生不同阶段反复出现的主线。`,strength:d.strength,shadow:d.shadow,growth:d.growth,compound:compound(steps)}}
function position(kind,n){const d=number(n);const angle={birthday:`${positionIntro.birthday} 你的生日数是${n}。${d.archetype}`,attitude:`${positionIntro.attitude} 你的态度数是${n}。${n===11?'你往往先感受气氛和细节，而不只是看表面发生了什么。':''}${d.archetype}`,birthYear:`${positionIntro.birthYear} 你的出生年数是${n}。${d.archetype}`};return{lead:angle[kind],keywords:d.keywords}}
function frequency(n,count,{isHighest=false}={}){const d=number(n),level=concentration[Math.min(count,4)];if(count===0)return{level,heading:`数字${n} · 空缺`,subtitle:`你的出生日期中没有出现${n}`,reason:`${n}没有直接出现在你的出生日期中，所以这里把它标记为空缺数字。`,sections:[['数字'+n+'代表什么',d.archetype],['为什么显示空缺',`因为${n}没有直接出现在你的出生日期中，所以它没有被出生数字重复加强。`],['这不代表什么',`这不代表你没有${d.keywords[0]}的能力，也不代表你不能拥有${n}的特质。`],['可以怎样发展',d.growth]]};const presence=count===1?`${n}出现1次，说明你具备它的基本倾向，但它不会压过其他数字成为特别强烈的习惯。`:count===2?`${n}出现2次，${d.keywords.slice(0,2).join('、')}在你身上会更加醒目，也更容易在日常选择中自然启动。`:count===3?`${n}出现3次，已经是出生数字里非常醒目的部分。它的优势和需要留意的一面都会更明显。`:`${n}出现${count}次，能量非常集中。它既可能成为很强的能力，也更容易被过度使用；这并不代表等级更高。`;return{level,heading:`数字${n} · ${level}`,subtitle:`出生日期中出现${count}次`,reason:isHighest?`${n}是你出生日期里出现次数最多的数字之一，因此它是这张出生数字图里比较醒目的部分。`:`你正在查看出生日期中出现${count}次的数字${n}。`,sections:[['数字'+n+'代表什么',d.archetype],['在你身上',presence],['发挥得好时',d.strength],['容易过头时',d.shadow],['怎么平衡',d.growth]]}}
function coreRelation(life,frequencyCount,present,steps){const d=number(life),label=frequencyCount===0?'成长型核心':frequencyCount===1?'存在型核心':'强化型核心';const text=frequencyCount===0?`你的生命路径是${life}，但${life}并没有直接出现在出生日期中。这形成了一个很有意思的组合：人生主线强调${d.keywords.join('、')}，但这些不是出生数字里反复加强的部分。换句话说，${life}更像需要逐渐学会的能力，而不是一开始最熟悉的做事方式。随着经验增加，你会越来越需要练习：${d.growth}`:frequencyCount===1?`你的生命路径是${life}，出生日期中也出现了1次${life}。这说明你对这条人生主线并不陌生，但仍需要在经验中把它发展得更稳定。`:`你的生命路径是${life}，它在出生日期中出现${frequencyCount}次。你对这条主线相当熟悉；真正的功课不是获得它，而是避免过度使用，并让它保持平衡。`;return{label,question:'你的生命路径，是不是你本来就熟悉的数字？',text,evidence:`生命路径 ${steps.join('/')}；出生日期实际出现 ${present}；数字${life}出现${frequencyCount}次 → ${label}`}}
function pinnacle(n){const d=number(n);return`这一阶段更强调${d.keywords.join('、')}。${d.archetype} 在这个年龄段，可以把注意力放在：${d.growth}`}
function challenge(n){const d=number(n);return n===0?'这一阶段的挑战不集中在某一个单一数字上。你需要根据实际处境辨认问题的重点，并学习在不确定中作出自己的选择。':`这一阶段的挑战与${n}有关。${d.shadow} 需要练习的是：${d.growth}`}
function personalYear(n,year){const d=number(n);return{title:`${year} 对你来说是个人流年 ${n}`,lead:`今年更适合把注意力放在${d.keywords.join('、')}上。${d.archetype}`,focus:d.strength,watch:d.shadow,note:'个人流年每年变化，不会改变你的出生数字。'}}
const pairCopy={
'7-6':{type:'成长张力',title:'独立理解与进入关系',text:'7需要空间、观察和独立判断；6强调关系、照顾、责任和参与。两者同时存在时，你一方面想先把事情理解清楚、保留自己的空间，另一方面又会遇到需要回应关系和承担责任的情境。这不是互相冲突，而是需要学习：既不为关系放弃自己的判断，也不因需要独处而退出所有责任。',integration:'7的洞察力会让6的照顾不只是情绪性的付出，而是更能理解对方真正需要什么。'},
'9-6':{type:'支持关系',title:'理想与具体照顾',text:'9和6都会把注意力放在人与意义上。9更关心整体、理想和事情带来的长远影响；6更关心具体关系、承诺和日常照顾。',integration:'9为6提供更大的价值方向，6则把这些关心落实到真实关系和行动中。需要留意的是，两者走得太重时都可能承担过多、对别人投入过多。'},
'1-6':{type:'互补关系',title:'自我与责任的平衡',text:'1强调自己的决定和方向，6强调关系中的责任。你可能会在“我真正想要什么”和“别人需要我做什么”之间来回衡量。',integration:'结合得好时，你能够在照顾别人时保留自己的立场，也能让个人决定考虑到现实关系。'},
'11-4':{type:'成长张力',title:'灵感与落实',text:'11强调感受、直觉和灵感，4强调结构、秩序和落实。它们并不是互相否定，而是在提醒你：感受到的东西还需要找到现实形式。',integration:'11提供方向和启发，4负责把它拆成步骤、计划和可以完成的成果。'},
'3-4':{type:'互补关系',title:'表达与建设',text:'3带来表达、试验和创造，4习惯规划、执行和建立秩序。一个让想法流动，一个让想法真正完成。',integration:'保留4的执行力，同时给3一些试错空间，创造才不会被计划困住，计划也不会失去活力。'}
};
function relation(source,target){const direct=pairCopy[`${source}-${target}`]||pairCopy[`${target}-${source}`];if(direct)return direct;const a=number(source),b=number(target);return{type:'需要整合',title:`${a.title}与${b.title}`,text:`${source}更强调${a.keywords.slice(0,2).join('、')}，${target}则把注意力带向${b.keywords.slice(0,2).join('、')}。你会在不同场景中使用这两种方式，它们不是互相推翻的答案。`,integration:`让${source}的${a.keywords[0]}支持${target}的${b.keywords[0]}，同时留意两者各自走得太重时的表现。`}}
function integrated(result){const life=result.lifePath.value,frequency=result.birthFrequency;const ranked=Object.entries(frequency).filter(([,v])=>v>0).map(([n,v])=>({number:+n,count:v})).sort((a,b)=>b.count-a.count||a.number-b.number);const dominant=ranked[0],secondary=ranked[1];const candidates=[];for(const item of ranked.slice(0,3))if(item.number!==life)candidates.push(item.number);for(const n of [result.birthday.value,result.attitude.value])if(n!==life&&!candidates.includes(n))candidates.push(n);const relations=candidates.slice(0,4).map(n=>({source:n,target:life,...relation(n,life)}));const leadNames=[dominant,secondary].filter(Boolean).map(x=>`${x.number}的${number(x.number).keywords.slice(0,2).join('与')}`);const summary=`你天然更熟悉${leadNames.join('，以及')}，而长期生命路径${life}把你带向${number(life).keywords.slice(0,3).join('、')}。这些数字不是互相矛盾的人格标签：出生数字是你较顺手的起点，生命路径是需要长期发展的方向。你的成长重点，是把熟悉的能力真正带进${life}所指向的现实生活。`;return{dominant,secondary,relations,summary,timeScale:{long:`长期主线：生命路径 ${life} · ${number(life).title}`,stage:`当前章节：高峰周期与阶段挑战会随年龄变化，不会把你变成另一个数字。`,year:`今年天气：个人流年 ${result.personalYear.value} 只描述 ${result.personalYear.year} 年更值得关注的内容。`}}}
function cycleConnection(life,pinnacleNumber){const known=relation(pinnacleNumber,life);return`你的长期主线${life}强调${number(life).keywords.slice(0,2).join('、')}；这一阶段的${pinnacleNumber}强调${number(pinnacleNumber).keywords.slice(0,2).join('、')}。${known.integration}`}
function yearConnection(life,yearNumber){if(life===yearNumber)return`生命路径${life}是长期主线，个人流年${yearNumber}只是今年的天气。今年会让你更集中地看见${number(life).keywords.slice(0,3).join('、')}这些长期功课；它不是一个新身份，而是对原有主线的阶段性强调。`;const known=relation(yearNumber,life);return`生命路径${life}是长期主线，个人流年${yearNumber}只是今年的天气。${known.text} ${known.integration}`}
root.NumerologyContent={numbers,concentration,number,compound,lifePath,position,frequency,coreRelation,pinnacle,challenge,personalYear,relation,integrated,cycleConnection,yearConnection};
})(typeof globalThis!=='undefined'?globalThis:this);
