(function(root,factory){const api=factory(typeof require==='function'?require('./numerology_core.js'):root.Numerology,typeof require==='function'?require('./relationship_content.js'):root.RelationshipContent);if(typeof module==='object'&&module.exports)module.exports=api;else root.RelationshipEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(N,C){
const base=n=>({11:2,22:4,33:6}[n]||n),key=(a,b)=>[base(a),base(b)].sort((x,y)=>x-y).join('-');
const pairThemes={'4-6':'responsibility_modes','6-7':'closeness_space','2-7':'closeness_space','3-7':'expression_reflection','4-5':'stability_change','6-9':'care_meaning','1-2':'autonomy_connection','4-9':'vision_grounding','4-11':'vision_grounding','1-6':'autonomy_connection'};
function classify(numberA,numberB,sourceA,sourceB){const same=base(numberA)===base(numberB),theme=same?'shared_number':pairThemes[key(numberA,numberB)]||'generic_difference',meta=C.themes[theme]||C.themes.generic_difference;return{rule:'relationship_interpretation_rule',types:[...meta.kind],sourceA,numberA,sourceB,numberB,theme};}
function ageAt(date,now=new Date()){let age=now.getFullYear()-date.year;if(now.getMonth()+1<date.month||(now.getMonth()+1===date.month&&now.getDate()<date.day))age--;return age}
function stageOf(result,now){const age=ageAt(result.date,now);let index=result.pinnacleAges.findIndex(([s,e])=>age>=s&&(e===null||age<=e));if(index<0)index=0;return{age,index,pinnacle:result.pinnacles[index],challenge:result.challenges[index],range:result.pinnacleAges[index]}}
function ranked(r){return Object.entries(r.birthFrequency).filter(([,count])=>count>0).map(([number,count])=>({number:+number,count})).sort((a,b)=>b.count-a.count||a.number-b.number)}
function relationCandidates(a,b){const rows=[classify(a.lifePath.value,b.lifePath.value,'lifePath','lifePath')];const ar=ranked(a),br=ranked(b);if(br[0])rows.push(classify(a.lifePath.value,br[0].number,'lifePath','birthFrequency'));if(ar[0])rows.push(classify(ar[0].number,b.lifePath.value,'birthFrequency','lifePath'));for(const x of ar.slice(0,3))for(const y of br.slice(0,3)){const item=classify(x.number,y.number,'birthFrequency','birthFrequency');if(item.theme!=='generic_difference')rows.push(item)}rows.push(classify(a.birthday.value,b.birthday.value,'birthday','birthday'));rows.push(classify(a.attitude.value,b.attitude.value,'attitude','attitude'));const seen=new Set;return rows.filter(r=>{const id=`${r.theme}:${r.numberA}:${r.numberB}`;if(seen.has(id))return false;seen.add(id);return true}).slice(0,5)}
function bridges(a,b){const out=[];for(const item of ranked(b).slice(0,3))if(a.birthFrequency[item.number]===0)out.push({number:item.number,from:'你',to:'对方',count:item.count});for(const item of ranked(a).slice(0,3))if(b.birthFrequency[item.number]===0)out.push({number:item.number,from:'对方',to:'你',count:item.count});if(a.birthFrequency[base(b.lifePath.value)]===0)out.unshift({number:base(b.lifePath.value),from:'你',to:'对方',source:'lifePath'});return out.filter((x,i,arr)=>arr.findIndex(y=>y.number===x.number&&y.from===x.from)===i).slice(0,3)}
function analyze(isoA,isoB,year=new Date().getFullYear(),now=new Date()){const a=N.calculate(isoA,year),b=N.calculate(isoB,year),relations=relationCandidates(a,b),common=[];for(let n=1;n<=9;n++)if(a.birthFrequency[n]&&b.birthFrequency[n])common.push({number:n,countA:a.birthFrequency[n],countB:b.birthFrequency[n]});const commonMissing=[];for(let n=1;n<=9;n++)if(!a.birthFrequency[n]&&!b.birthFrequency[n])commonMissing.push(n);const resonance=relations.filter(x=>x.types.includes('resonance')),tension=relations.filter(x=>x.types.includes('tension')).slice(0,3),complement=relations.filter(x=>x.types.includes('complement'));const themes=[...new Set([...tension,...complement,...resonance].map(x=>x.theme))].slice(0,4);return{version:1,year,a,b,stageA:stageOf(a,now),stageB:stageOf(b,now),common,commonMissing,relations,resonance,complement, tension,bridges:bridges(a,b),themes,summary:classify(a.lifePath.value,b.lifePath.value,'lifePath','lifePath')}}
return{analyze,classify,stageOf,ageAt};
});
